import Sidebar from "@/components/sidebar/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box, CssBaseline, Grid } from "@mui/material";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smart Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline>
          <Grid container p={1} spacing={2}>
            <Grid item xs={2} md={1}>
              <Sidebar />
            </Grid>
            <Grid item xs={10} md={11} mt={1.5}>
              <Header />
              {children}
            </Grid>
          </Grid>
        </CssBaseline>
      </body>
    </html>
  );
}
